//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL_WILFREDO_VALVERDE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        public decimal ID_ALUMNO { get; set; }
        public string DNI { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<short> ESTADO { get; set; }
    }
}
