//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL_WILFREDO_VALVERDE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULA
    {
        public decimal ID_MATRICULA { get; set; }
        public Nullable<decimal> ID_ALUMNO { get; set; }
        public Nullable<decimal> ID_MODALIDAD { get; set; }
        public Nullable<decimal> ID_VACANTE { get; set; }
        public string FECHA_MATRICULA { get; set; }
        public string FECHA_ANULACION { get; set; }
    }
}
