//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL_WILFREDO_VALVERDE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TODOITEM
    {
        public decimal ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTimeOffset> CREATION_TS { get; set; }
        public Nullable<short> DONE { get; set; }
    }
}
