//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL_WILFREDO_VALVERDE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACANTE
    {
        public decimal ID_VACANTE { get; set; }
        public Nullable<decimal> ID_CURSO { get; set; }
        public Nullable<decimal> ID_SECCION { get; set; }
        public Nullable<decimal> CANTIDAD_VACANTE { get; set; }
    }
}
